.TH BALISTICA 1 "Version @VERSION@" "Steven Oliver" "Balistica"


.SH "NAME"
balistica \- A simple open source ballistics calculator


.SH SYNOPSIS
.TP 6
\fBctags\fP [\fBoptions\fP] [\fIfile(s)\fP]
.TP 6
\fBetags\fP [\fBoptions\fP] [\fIfile(s)\fP]


.SH "DESCRIPTION"
The \fBctags\fP and \fBetags\fP programs (hereinafter collectively referred to

.SH "OPTIONS"

Despite the wealth of available options, defaults are set so that \fBctags\fP

.TP 5
.B \-a
Equivalent to \fB\-\-append\fP.

.SH "AUTHOR"
Steven Oliver <oliver.steven@gmail.com>

