#! /usr/bin/env python
# encoding: utf-8

conversion = [
'conversion/Angle.vala',
'conversion/Temperature.vala',
]

lib_balistica = [
'Atmosphere.vala',
'Greenhill.vala',
'LibBalistica.vala',
'Miller.vala',
'Retard.vala',
'Retrieve.vala',
'Solve.vala',
'Windage.vala',
'Zero.vala',
]

prog = bld.new_task_gen (
        features = 'cc cprogram',
        target = 'lib-balistica',
        uselib = 'GLIB',
        packages = 'glib-2.0 config',
        source = conversion + lib_balistica
)

