.TH BALISTICA 1 "Version @VERSION@" "Steven Oliver" "Balistica"


.SH "NAME"
balistica \- A simple open source external balistics calculator


.SH SYNOPSIS
.TP 6
\fBbalistica\fP [\fBoptions\fP]


.SH "DESCRIPTION"
\fBbalisitica\fP is a very simple external balistics calculator. 
Currently it can only do one of two things. Compute the twist and
stability factors of a round using the Miller Twist Rate or the 
twist rate using the Greenhill formula.

.SH "OPTIONS"

.SH "AUTHOR"
Steven Oliver <oliver.steven@gmail.com>

