#! /usr/bin/env python
# encoding: utf-8

src = [
'Balistica.vala',
'CmdHandler.vala',
'Miller.vala',
'Greenhill.vala'
]

app = bld.program(
        target = 'balistica',
        vapi_dirs = '../vapi',
        threading = True,
        uselib = 'GLIB',
        packages = 'glib-2.0 libxml-2.0 config',
        source = src
)

