#! /usr/bin/env python
# encoding: utf-8

src = [
'Balistica.vala',
'CmdHandler.vala',
]

conversion = [
'conversion/Angle.vala',
'conversion/Temperature.vala',
]

lib_balistica = [
'lib-balistica/Atmosphere.vala',
'lib-balistica/Miller.vala',
'lib-balistica/Greenhill.vala',
'lib-balistica/Retard.vala',
'lib-balistica/Windage.vala',
'lib-balistica/Zero.vala',
]

db = [
'db/Database.vala',
]

app = bld.program(
        target = 'balistica',
        vapi_dirs = '../vapi',
        threading = True,
        uselib = 'GLIB',
        packages = 'glib-2.0 config',
        source = src + conversion + lib_balistica
)

